-- 3 Write a program of mark sheet with displays the SEAT_NO, NAME OF STUDENT, marks 
-- of 5 subjects, total of 5 subjects and percentage, also display the class of student
-- based on the value of percentage.

-- CREATE TABLE MARKSHEET (
--     SEAT_NO NUMBER(5),
--     NAME VARCHAR2(20),
--     RDBMS NUMBER(3),
--     JAVA NUMBER(3),
--     OS NUMBER(3),
--     DS NUMBER(3),
--     PHP NUMBER(3),
--     TOTAL NUMBER(3),
--     PERCENTAGE NUMBER(9,2),
--     CLASS VARCHAR2(10)
-- );

SET SERVEROUTPUT ON
SET VERIFY OFF
SET FEEDBACK OFF

ACCEPT SEAT_NO PROMPT "ENTER SEAT NUMBER: "
ACCEPT NAME PROMPT "ENTER NAME: "
ACCEPT RDBMS PROMPT "ENTER MARKS FOR RDBMS: "
ACCEPT JAVA PROMPT "ENTER MARKS FOR JAVA: "
ACCEPT OS PROMPT "ENTER MARKS FOR OS: "
ACCEPT DS PROMPT "ENTER MARKS FOR DS: "
ACCEPT PHP PROMPT "ENTER MARKS FOR PHP: "

-- RDBMS
-- JAVA
-- OS
-- DS
-- PHP

DECLARE
    SEAT_NO MARKSHEET.SEAT_NO%TYPE;
    NAME MARKSHEET.NAME%TYPE;
    RDBMS MARKSHEET.RDBMS%TYPE;
    JAVA MARKSHEET.JAVA%TYPE;
    OS MARKSHEET.OS%TYPE;
    DS MARKSHEET.DS%TYPE;
    PHP MARKSHEET.PHP%TYPE;
    TOTAL MARKSHEET.TOTAL%TYPE;
    PERCENTAGE MARKSHEET.PERCENTAGE%TYPE;
    CLASS MARKSHEET.CLASS%TYPE;
BEGIN
    SEAT_NO := &SEAT_NO;
    NAME := '&NAME';
    RDBMS_MARK := &RDBMS;
    JAVA_MARK := &JAVA;
    OS_MARK := &OS;
    DS_MARK := &DS;
    PHP_MARK := &PHP;
    TOTAL := RDBMS_MARK + JAVA_MARK + OS_MARK + DS_MARK + PHP_MARK;

    DBMS_OUTPUT.PUT_LINE('SEAT NUMBER: ' || TOTAL);

    PERCENTAGE := TOTAL / 5;
    IF PERCENTAGE >= 80 THEN
        CLASS := 'DISTINCTION';
    ELSIF PERCENTAGE >= 60 THEN
        CLASS := 'FIRST CLASS';
    ELSIF PERCENTAGE >= 40 THEN
        CLASS := 'SECOND CLASS';
    ELSIF PERCENTAGE >= 35 THEN
        CLASS := 'PASS CLASS';
    ELSE
        CLASS := 'FAIL';
    END IF;
    DBMS_OUTPUT.PUT_LINE('SEAT NUMBER: ' || SEAT_NO);
    DBMS_OUTPUT.PUT_LINE('NAME: ' || NAME);
    DBMS_OUTPUT.PUT_LINE('RDBMS: ' || RDBMS);
    DBMS_OUTPUT.PUT_LINE('JAVA: ' || JAVA);
    DBMS_OUTPUT.PUT_LINE('OS: ' || OS);
    DBMS_OUTPUT.PUT_LINE('DS: ' || DS);
    DBMS_OUTPUT.PUT_LINE('PHP: ' || PHP);
    DBMS_OUTPUT.PUT_LINE('TOTAL: ' || TOTAL);
    DBMS_OUTPUT.PUT_LINE('PERCENTAGE: ' || PERCENTAGE);
    DBMS_OUTPUT.PUT_LINE('CLASS: ' || CLASS);
    INSERT INTO MARKSHEET VALUES(SEAT_NO, NAME, RDBMS, JAVA, OS, DS, PHP, TOTAL, PERCENTAGE, CLASS);
END;
/
