-- Write a trigger to restrict user form using the table on ‘Sunday’.
--
-- CREATE TABLE C_AREA (RADIUS NUMBER (5), AREA NUMBER (14,2));

CREATE OR REPLACE TRIGGER TRG_C_AREA_new
BEFORE INSERT OR UPDATE OR DELETE
ON C_AREA
FOR EACH ROW
BEGIN
    IF (TRIM(TO_CHAR(SYSDATE,'DAY'))='WEDNESDAY') THEN
        RAISE_APPLICATION_ERROR(-20001,'TABLE C_AREA IS NOT ACCESSIBLE ON SUNDAY');
    END IF;
END;
/
-- Table created.
-- Trigger created.


CREATE OR REPLACE TRIGGER TRG_C_AREA_new
BEFORE INSERT OR UPDATE OR DELETE
ON C_AREA
FOR EACH ROW
    WHEN (TRIM(TO_CHAR(SYSDATE,'DAY'))='SUNDAY') 
BEGIN
        RAISE_APPLICATION_ERROR(-20001,'TABLE C_AREA IS NOT ACCESSIBLE ON SUNDAY');
END;
/